version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: caliandra_postgres
    environment:
      POSTGRES_USER: caliandra
      POSTGRES_PASSWORD: caliandra123
      POSTGRES_DB: ecommerce
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
